//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMe.Bot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindMe.Bot.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager selected successfully..
        /// </summary>
        internal static string ChangeManagerCardFinalMessage {
            get {
                return ResourceManager.GetString("ChangeManagerCardFinalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter manager name.
        /// </summary>
        internal static string ChangeManagerCardTitle {
            get {
                return ResourceManager.GetString("ChangeManagerCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        internal static string NoResultsMessage {
            get {
                return ResourceManager.GetString("NoResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team time report for the previous week.
        /// </summary>
        internal static string ReportConsentDescription {
            get {
                return ResourceManager.GetString("ReportConsentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your report is ready.
        /// </summary>
        internal static string ReportIsReadyMessageText {
            get {
                return ResourceManager.GetString("ReportIsReadyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report uploading was declined.
        /// </summary>
        internal static string ReportWasDeclinedMessageText {
            get {
                return ResourceManager.GetString("ReportWasDeclinedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search has been completed..
        /// </summary>
        internal static string SearchEmployeeCardFinalMessage {
            get {
                return ResourceManager.GetString("SearchEmployeeCardFinalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter employee name.
        /// </summary>
        internal static string SearchEmployeeCardTitle {
            get {
                return ResourceManager.GetString("SearchEmployeeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected person is already an employee manager..
        /// </summary>
        internal static string SelectedPersonIsAlreadyAEmployeeManager {
            get {
                return ResourceManager.GetString("SelectedPersonIsAlreadyAEmployeeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set your status for the current shift..
        /// </summary>
        internal static string ShiftStartStatusUserNotification {
            get {
                return ResourceManager.GetString("ShiftStartStatusUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, sign in to be able to use FindMe app.
        /// </summary>
        internal static string SignInCardTitle {
            get {
                return ResourceManager.GetString("SignInCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your status is due to expire in 10 minutes. Please, update it..
        /// </summary>
        internal static string StatusExpiredUserNotification {
            get {
                return ResourceManager.GetString("StatusExpiredUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is not set.
        /// </summary>
        internal static string StatusIsNotSetText {
            get {
                return ResourceManager.GetString("StatusIsNotSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {user}&apos;s status is overdue by 15 minutes..
        /// </summary>
        internal static string StatusOverdueManagerNotification {
            get {
                return ResourceManager.GetString("StatusOverdueManagerNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your status has gone overdue by 15 minutes and your manager has been alerted. Please, update your status..
        /// </summary>
        internal static string StatusOverdueUserNotification {
            get {
                return ResourceManager.GetString("StatusOverdueUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received a status request from {name}. Please update it now..
        /// </summary>
        internal static string StatusRequestMessage {
            get {
                return ResourceManager.GetString("StatusRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status update request was sent successfully..
        /// </summary>
        internal static string StatusUpdateRequestSuccessMessage {
            get {
                return ResourceManager.GetString("StatusUpdateRequestSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAIAAADYYG7QAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABESURBVFhH7c4xAQAwDASh+tf5QiqBNcOhgLdjCkkhKSSFpJAUkkJSSApJISkkhaSQFJJCUkgKSSEpJIWkkBSSQnIstH1jmg1p8gZ4dwAAAABJRU5ErkJggg==.
        /// </summary>
        internal static string UnknownAvatarBase64 {
            get {
                return ResourceManager.GetString("UnknownAvatarBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This conversation is not supported..
        /// </summary>
        internal static string UnsupportedConversation {
            get {
                return ResourceManager.GetString("UnsupportedConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! You can change this any time by typing &apos;Change hours&apos;..
        /// </summary>
        internal static string UpdateHoursCompleteMessage {
            get {
                return ResourceManager.GetString("UpdateHoursCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid form data. Please, try again..
        /// </summary>
        internal static string UpdateHoursErrorMessage {
            get {
                return ResourceManager.GetString("UpdateHoursErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set your working hours for this week..
        /// </summary>
        internal static string UpdateHoursWeeklyNotificationText {
            get {
                return ResourceManager.GetString("UpdateHoursWeeklyNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops, something went wrong. Please, try again..
        /// </summary>
        internal static string UpdateManagerErrorText {
            get {
                return ResourceManager.GetString("UpdateManagerErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been assigned as the manager of {name}..
        /// </summary>
        internal static string UpdateManagerNotificationNewManagerMessage {
            get {
                return ResourceManager.GetString("UpdateManagerNotificationNewManagerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been unassigned as the manager of {name}..
        /// </summary>
        internal static string UpdateManagerNotificationPreviousManagerMessage {
            get {
                return ResourceManager.GetString("UpdateManagerNotificationPreviousManagerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {name} has been assigned as your manager..
        /// </summary>
        internal static string UpdateManagerNotificationUserMessage {
            get {
                return ResourceManager.GetString("UpdateManagerNotificationUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manager for the current user has been successfully updated..
        /// </summary>
        internal static string UpdateManagerSuccessText {
            get {
                return ResourceManager.GetString("UpdateManagerSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot designate yourself as a manager..
        /// </summary>
        internal static string UpdateManagerYouCannotAssignYourselfText {
            get {
                return ResourceManager.GetString("UpdateManagerYouCannotAssignYourselfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User status has been successfully updated..
        /// </summary>
        internal static string UpdateStatusSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateStatusSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are signed out..
        /// </summary>
        internal static string UserSignedOutMessage {
            get {
                return ResourceManager.GetString("UserSignedOutMessage", resourceCulture);
            }
        }
    }
}
